name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Используем Виртуальную машину (Ubuntu последней версии)
    steps:
    - name: Checkout project # Извлекаем репозиторий на виртуальную машину
      uses: actions/checkout@v3
    - name: Create SSH files 1  # Подготавливаем SSH файлы (создаём приватный ключ ssh)
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
    - name: Create SSH files 2  # Подготавливаем SSH файлы (создаём конфиг ssh)
      run: |
        cat >>~/.ssh/config <<END
        Host Remote_Server
          HostName ${{secrets.SSH_HOST}}
          User ${{secrets.SSH_USER}}
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
    - name: Copy project  # Копируем проект на удаленный сервер (публичный ключ должен быть прописан в authorized_keys на удаленном сервере)
      run: |
        scp -r /home/runner/work/weather_telegram_bot/weather_telegram_bot Remote_Server:${{secrets.PATH_TO_PROJECT}}
    - name: Create enviroment variable on server # Создаем переменную окружения на сервере
      run: |
        ssh Remote_Server "cd /etc && echo 'BOT_API_KEY=${{secrets.BOT_API_KEY}}' > environment"
    - name: Create service and run bot # Создаем сервис и запускаем приложение
      run: |
        ssh Remote_Server 'systemctl stop WeatherBot && 
                          cd /etc/systemd/system &&
                          echo "[Unit]
                          Description=EasySlave
                          After=network.target

                          [Service]
                          Environment="BOT_API_KEY=$BOT_API_KEY"
                          Type=simple
                          User=root
                          ExecStart=${{secrets.PATH_TO_PROJECT}}/venv/bin/python ${{secrets.PATH_TO_PROJECT}}/bot.py
                          KillMode=process
                          Restart=always
                          RestartSec=10

                          [Install]
                          WantedBy=multi-user.target" > WeatherBot.service
                          '

#Устанавливаем менеджер пакетов и модуль виртуального окружения
#apt --yes install python3-venv python3-pip
#
##Создаём виртуальное окружение и устанавливаем пакеты
#cd ${{secrets.PATH_TO_PROJECT}}
#python3 -m venv venv
#source venv/bin/activate
#pip install -r requirements.txt
#
##Запускаем сервис
#systemctl enable WeatherBot
#systemctl start WeatherBot