name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup
      - run: echo ${{ secrets.SSH_KEY}}
      - run: echo Hello World!
      - run: ls
      - run: whereis requirements.txt
      - run cat requirements.txt
      # Deploy
