# This workflow will copy project on remote server.

name: "Deploy Telegram Bot"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy files on remote server
        run: |
        ls -a
        cd ..
        ls -a
