name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Copy project
      run: |
        ls
        ls -a
        pwd
        scp -r /home/runner/work/weather_telegram_bot/ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.PATH_TO_PROJECT}}